# Generated by Django 5.0.2 on 2024-03-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_foodtype_fooditem_created_at_fooditem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='meals.foodtype'),
            preserve_default=False,
        ),
    ]
