# Generated by Django 5.0.2 on 2024-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_fooditem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
