# Generated by Django 5.0.2 on 2024-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(default='Image.png', upload_to='meales/types'),
            preserve_default=False,
        ),
    ]
