# Generated by Django 5.0.2 on 2024-03-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_rename_total_price_foodorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='order_time',
        ),
    ]
