# Generated by Django 5.0.2 on 2024-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_foodorder_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=255),
        ),
    ]
