# Generated by Django 5.0.2 on 2024-03-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service'),
        ('meals', '0013_remove_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='terminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.terminal'),
            preserve_default=False,
        ),
    ]
