# Generated by Django 5.0.2 on 2024-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelimage_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='feature',
            field=models.JSONField(default=[]),
        ),
    ]
