# Generated by Django 5.0.2 on 2024-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_room_rating_alter_hotel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='checkout_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
