# Generated by Django 5.0.2 on 2024-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_reservation_checkout_date_reservation_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='days',
            new_name='nights',
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
