# Generated by Django 5.0.2 on 2024-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_hotel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=-1.3275419276289535, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=36.892774467385905, max_digits=22),
            preserve_default=False,
        ),
    ]
